language: cpp
compiler:
  - g++
os:
  - linux
dist: "trusty"  
install:
  - sudo apt install -y git make libssl-dev g++-5
git:
  depth: 1
branches:
  only:
    - master
script:
  - git clone -b ubuntu-x64 --single-branch https://github.com/ipop-project/3rd-Party-Libs.git external/3rd-Party-Libs --depth 1
  - cd trunk/build
  - make
  
